[ODPR-1424] - SUB-16: update content on RegistrationConfirmationPage
hmrc/digital-platform-reporting-register-frontend pull request #107
Opened 2024-09-04 14:31 UTC by Rabina-Rai

### Description

- Adds paragraph in already existing 'RegistrationConfirmation' page
- Paragraph requires 'businessName' (for orgs) and date & time to be added 

Add a link to the relevant story in Jira
[ODPR-1424](https://jira.tools.tax.service.gov.uk/browse/ODPR-1424)

### Checklist PR Raiser

##### Before creating PR

- [x] Have you run the tests?
- [x] Have you run the journey tests? (where applicable)
- [x] Have you addressed warnings where appropriate?
- [x] Have you rebased against the current version of main?
- [ ] Have you checked code coverage isn’t lower than previously?
- [x] Have you checked to ensure all dependencies are up-to-date?

##### After PRs been raised

- [ ] Have you checked the PR Builder passes?

### Checklist PR Reviewer

##### Before Reviewing

- [x] Have you pulled the branch down?
- [x] Have you assigned yourself to the PR?
- [x] Have you moved the task to “in review” on JIRA?
- [x] Have you checked to ensure all dependencies are up-to-date?
- [x] Have you checked to ensure branch has been rebased against the current version of main?

##### Whilst Reviewing

- [x] Have you run the tests?
- [ ] Have you run the journey tests?
- [ ] Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing

- [ ] Have you checked for merge conflicts or any changes in the current main that may affect the current pull request?
  i.e. does it need another rebase?
- [ ] Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ] Have you moved the task to “in pipeline” on Jira?

2024-09-05 08:37 UTC, georgievh requested changes

2024-09-05 08:37 UTC, georgievh commented on app/controllers/CheckYourAnswersController.scala
> +              SubscriptionDetails(response, request, registrationType, answers.get(BusinessTypePage), businessName)
You can create an apply method in the SubscriptionDetails and pass response, request and answers only. You can move the logic of creating the object there which will simplify the controller a bit and will provide better testability.

2024-09-05 08:37 UTC, georgievh commented on app/controllers/CheckYourAnswersController.scala
> +  private def getBusinessName(userAnswers: UserAnswers): Option[String] = {
With the refactoring above, this can move in the SubscriptionDetails

2024-09-05 08:37 UTC, georgievh commented on app/models/pageviews/RegistrationConfirmationViewModel.scala
> +                                              subscribedTime: String,
You don't need two values here. You can format the string with the following formatter:
DateTimeFormatter.ofPattern("d MMMM yyyy 'at' hh:mma (z)").withZone(ZoneId.of("GMT"))

2024-09-05 08:37 UTC, georgievh commented on app/models/pageviews/RegistrationConfirmationViewModel.scala
> +      val subscribedDate = dprsUserId._2.atZone(ZoneId.of("Europe/London")).format(dateFormat())
Use the formatter I provided in my previous comment.

2024-09-05 08:37 UTC, georgievh commented on test/controllers/CheckYourAnswersControllerSpec.scala
> +              val subscriptionDetails = SubscriptionDetails(subscriptionResponse, expectedSubscriptionRequest, RegistrationType.PlatformOperator, Some(BusinessType.LimitedCompany), Some("name"))
Perhaps creating SubscriptionDetailsBuilder will be useful to generate default SubscriptionDetails for testing.

2024-09-05 15:58 UTC, georgievh requested changes

2024-09-05 15:58 UTC, georgievh commented on app/models/SubscriptionDetails.scala
> +  def apply(response: SubscriptionResponse, request: SubscriptionRequest, userAnswers: UserAnswers): SubscriptionDetails = {
Please write tests for all the branches inside the method.

2024-09-05 15:58 UTC, georgievh commented on app/models/pageviews/RegistrationConfirmationViewModel.scala
> +                                              businessName: String
Business name should be optional.

2024-09-05 15:58 UTC, georgievh commented on app/utils/DateTimeFormats.scala
> +    dateTimeFormatter.format(dateTime).replace("AM","am").replace("PM","pm")
If you use the formatter you don't need to replace the AM and PM as h:mma already does that.

2024-09-05 15:58 UTC, georgievh commented on app/utils/DateTimeFormats.scala
> +  private val dateTimeFormatter = DateTimeFormatter.ofPattern("d MMMM yyyy 'at' h:mma (z)").withZone(ZoneId.of("GMT"))
This formatter is too specific and unless we have a good name for it I would put it in the RegistrationConfirmationViewModel object.

2024-09-05 16:27 UTC, georgievh requested changes

2024-09-05 16:27 UTC, georgievh commented on app/views/RegistrationConfirmationView.scala.html
> +            @if(viewModel.isThirdParty) {
This block looks a bit strange to me. Can we discuss it please?

2024-09-06 15:49 UTC, georgievh approved these changes

2024-09-06 15:55 UTC, Alex-H-94 approved these changes
Requested approval.

2024-09-06 15:55 UTC, merged

2024-09-06 15:58 UTC, TheNickWilson approved these changes